title: click the secret link
description: Data scientist based in Gold Coast, specialising in AI and data analysis. Transforming complex data into actionable insights.
baseurl: "/hacked-jekyll" 
url: "https://anthropoleo.github.io"  

theme: hacked-jekyll

# Setting this to true to open all links in new tabs
newtab: true

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# SEO Tag configuration
title: Leo's business card
tagline: AI and Data Analysis Expertise from Gold Coast
author: Leo

# Sitemap configuration
defaults:
  -
    scope:
      path: ""
    values:
      sitemap: true

sass:
  sourcemap: never
