title: click the secret link
description: 
baseurl: "/hacked-jekyll" 
url: "https://anthropoleo.github.io"  

theme: hacked-jekyll

# Set this to true to open all links in new tabs
newtab: true

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
